timescale/pgai

- Dockerfile
- Makefile
- ai--0.1.0.sql
- test.sh
- tests.sql
- vm.sh
The _api_key parameter is now optional. If it is not passed, the GUC ai.openai_api_key is used.
> Make api key an optional parameter

- README.md
- docs/advanced.md
Now that api key is an optional variable, the docs and examples need to be updated. These are those updates.
> Documentation updates

- Makefile
- vm.sh
> Use PIP_BREAK_SYSTEM_PACKAGES env var instead of pip arg

- README.md
Move asdf plpython3u instructions to plpython3u section
> Move asdf plpython3u instructions to plpython3u section

- DEVELOPMENT.md
Doc review on the Develop guide.
> chore: doc review.

- sql/idempotent/04-cohere.sql
- tests/cohere.sql
Somehow missed this parameter previously.
> Add support for rank_fields parameter to cohere_rerank

- Dockerfile
- build.py
- sql/ai--0.4.0.sql
- sql/idempotent/007-scheduling.sql
- sql/idempotent/010-vectorizer-int.sql
- sql/idempotent/011-vectorizer-api.sql
- tests/contents/output.expected
- tests/privileges/function.expected
- tests/vectorizer/test_scheduling.py
- tests/vectorizer/test_vectorizer.py
We decided that support for pgcron is not necessary. Backing out the implementation.
> Remove pgcron scheduling implementation

- sql/ai--0.4.0.sql
- sql/idempotent/010-vectorizer-int.sql
- tests/vectorizer/test_vectorizer.py
Add tests to ensure that async vector index creation works
> Tests for vector index creation

- tests/conftest.py
Unnecessary check for pgcron in tests fixture. Pgcron is gone.
> Remove drop of pgcron in tests

- sql/ai--0.4.0.sql
- sql/idempotent/001-openai.sql
- sql/idempotent/011-vectorizer-int.sql
pgspot spotted some issues with openai_chat_complete_simple
i need to get pgspot running in CI so these issue don't slip by
> fix sql lint issues

- docs/self-hosting-vectorizer.md
- docs/vectorizer.md
> chore: doc review of self-hosted.

- docs/vectorizer-api-reference.md
- Add a missing word
- Fix incorrect description of `ai.indexing_none()`
- Add link to pgvectorscale for DiskANN index type
> chore: minor docs fixes

- .github/workflows/release-please.yml
> chore: release pgai container to dockerhub

- projects/pgai/pgai/cli.py
> Disable ddtracer by default

- examples/rag_report_demo_why_some_customers_donot_like_pizza.sql
The old url returns a 404, I found the working page at the updated url
> chore: update reference inline with url changes

- projects/pgai/README.md
Updates the pgai library readme with the content that's on the root of the project. This README is what's displayed in pypi.
> refactor: pypi readme

- projects/extension/tests/upgrade/init.sql
- projects/extension/tests/upgrade/test_upgrade.py
Add a vectorizer and a row to secret_permissions to the upgrade tests to make sure upgrades do the right thing.
> test: add a vectorizer and secret to upgrade tests

- projects/extension/build.py
The new development version is 0.4.2-dev
> chore: set current version to 0.4.2-dev

- projects/extension/Dockerfile
- projects/extension/justfile
move to postgres 17 for development
> chore: switch to postgres 17

- README.md
- docs/adding-embedding-integration.md
I believe it could be interesting to have a table with features supported per each model. This gives you quick visual info about what is and what isn't supported by pgai. I created the table based on the info we have in our README.
This is just a suggestion and I'm very happy to discard it.
> docs: add a table with each feature supported by model

- docs/openai.md
- docs/vectorizer-quick-start-openai.md
- docs/vectorizer-quick-start.md
- docs/vectorizer-worker.md
- docs/voyageai.md
Makes the use-case of the different installation options more clear.
> docs: rework vectorizer instructions

- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/vectorizer/test_vectorizer.py
Superusers should be able to create vectorizers on any table they wish, regardless of ownership.
> feat: allow superusers to create vectorizers on any table

- .github/workflows/release-please.yml
start adding also latest to the image published by release-please action.
> chore: includes latest tag on releases

- projects/extension/ai/anthropic.py
- projects/extension/ai/litellm.py
- projects/extension/ai/load_dataset.py
- projects/extension/ai/ollama.py
- projects/extension/ai/openai.py
- projects/extension/ai/secrets.py
- projects/extension/ai/voyageai.py
- projects/extension/build.py
- projects/extension/pyproject.toml
- projects/extension/tests/contents/test_contents.py
- projects/extension/tests/dump_restore/test_dump_restore.py
- projects/extension/tests/privileges/test_privileges.py
- projects/extension/tests/secrets/test_secrets.py
- projects/extension/tests/test_anthropic.py
- projects/extension/tests/test_cohere.py
- projects/extension/tests/test_litellm.py
- projects/extension/tests/test_load_dataset.py
- projects/extension/tests/test_ollama.py
- projects/extension/tests/test_openai.py
- projects/extension/tests/test_voyageai.py
- projects/extension/tests/text_to_sql/test_dump_restore.py
- projects/extension/tests/text_to_sql/test_text_to_sql.py
- projects/extension/tests/vectorizer/server.py
This enables some more linting rules in the extension, aligning linting rules across the pgai library and the extension.
> chore(extension): enable more linting rules

- docs/anthropic.md
Missed updating the docs as part of #386, whoops.
> docs: add anthropic_list_models

- projects/extension/build.py
Introduces the Actions class which acts as a container for all public-facing actions available in build.py.
To add a new action to the build.py, one need only add a new member function to the Actions class.
> chore: internal refactor build.py

- projects/extension/sql/idempotent/900-semantic-catalog-init.sql
- projects/extension/sql/idempotent/901-semantic-catalog-set.sql
- projects/extension/sql/idempotent/904-semantic-catalog-search.sql
- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
- projects/extension/sql/idempotent/909-text-to-sql-cohere.sql
- projects/extension/sql/idempotent/910-text-to-sql.sql
- projects/extension/sql/idempotent/999-privileges.sql
- projects/extension/sql/incremental/900-semantic-catalog.sql
1. made user prompt configurable
2. made system prompt configurable
3. cleaned up some code
4. added functions for deleting descriptions
this is pre-release code
> text-to-sql minor stuff

- README.md
1. improve layout by putting stuff in detail boxes and redoing the flow
2. add python method of doing RAG
> chore: improve quickstart

- docs/structured_retrieval/text_to_sql.md
- examples/text_to_sql/.gitignore
- examples/text_to_sql/README.md
- examples/text_to_sql/gen_desc.sql
- examples/text_to_sql/gen_embed.sql
- projects/extension/ai/semantic_catalog.py
- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
Adds a demo of the text-to-sql feature using the postgres_air dataset.
> feat(text_to_sql): demo

- projects/extension/sql/idempotent/014-parsing.sql
- projects/extension/sql/idempotent/015-vectorizer-api.sql
- projects/extension/tests/contents/output16.expected
- projects/extension/tests/contents/output17.expected
- projects/extension/tests/privileges/function.expected
- projects/extension/tests/vectorizer/test_parsing.py
This PR adds support for the Docling parser in the extension.
> feat: support docling parser in the extension

- docs/vectorizer-quick-start.md
- docs/vectorizer/quick-start.md
> fix: specify value in limit clause

- projects/pgai/DEVELOPMENT.md
Extend and clarify (hopefully) the development documentation for the library
> docs(pgai): improve the development docs for the pgai library

- projects/pgai/tests/vectorizer/extensions/conftest.py
I ran the pg container locally with very limited cpu and could at least in one out of 10 runs reproduce the deadlock that way. This connection closing seems to fix it. I don't really know what is happening here, but I found a few complains of schema dropping resulting in deadlocks, it seems like something in alembic is not quite correctly cleaned up.
> fix: flaky alembic tests

- projects/extension/build.py
addresses @JamesGuthrie comment: https://github.com/timescale/pgai/pull/507#pullrequestreview-2637546410
> build: ensure temp dir deleted regardless of errors in install_prior_py

- CONTRIBUTING.md
so it's correctly a hyperlink.
> fix: adjust docs link

- docs/security/handling-api-keys.md
> chore: update handling-api-keys.md

- docs/install/docker.md
Paste the correct link to docker-compose.yml
> fix: update docker compose example

- projects/extension/tests/test_cohere.py
- projects/pgai/pgai/cli.py
fixes a regression introduced in 3768c1c0a58e147fbeb6e720d7043f0fa6e0513a
> fix: do not exit when no extension installed

- projects/extension/tests/test_cohere.py
Since this test is failing randomly very often, and based on the confirmation we got from Cohere team, the result of the chat complete can't be deterministic at 100%. It means this test will keep failing randomly in time. 
In our particular case, we don't need to evaluate the result but just checking we do have a result.
> test: simplify cohere tests

- .github/workflows/huggingface-dataset.yml
- docs/security/privileges.md
- docs/vectorizer/quick-start-ollama.md
- docs/vectorizer/quick-start-openai.md
- scripts/generate_huggingface_dataset.py
Adds a script to generate the `timescale/pgai-docs` huggingface dataset from the documentation in this repository (docs/**/*.md).
A github action ensures that the dataset is kept up to date when docs change.
> feat: add timescale/pgai-docs dataset

- projects/pgai/pgai/vectorizer/embedders/openai.py
The openAI regular client API performs a lot of typecast operations when parsing API responses. On big responses, like what the vectorizer is expected to handle, it uses considerable CPU time to typecast and assert types.
The openAI embedder now uses an API that returns raw responses. The raw responses are decoded into a dict instead of custom types, which uses considerable less CPU.
https://www.loom.com/share/13043b12c2094871bad55a1fcef1cfc9?sid=383f3e28-83ac-4900-a9a5-c0a618f81b98
> perf: use openAI raw response to reduce CPU consumption

- projects/pgai/pgai/vectorizer/vectorizer.py
Using lateral join allows for constraints to be pushed into the query against the source table, which can be used to perform runtime chunk exclusion of chunks in a (compressed) hypertable, decreasing time take to fetch a chunk of work items.
> fix: force runtime chunk exclusion in fetch_work_query

- projects/extension/sql/idempotent/905-semantic-catalog-render.sql
PR fixes a bug where when creating a view like:
```
CREATE MATERIALIZED VIEW one_hour_transactions
WITH (timescaledb.continuous) AS
SELECT time_bucket('1 hour', time) AS bucket,
count(*) AS tx_count,
sum(fee) AS total_fee_sat,
sum(fee_usd) AS total_fee_usd,
stats_agg(fee) AS stats_fee_sat,
avg(size) AS avg_tx_size,
avg(weight) AS avg_tx_weight,
count(
CASE
WHEN (fee > output_total) THEN hash
ELSE NULL
END) AS high_fee_count
FROM transactions
WHERE (is_coinbase IS NOT TRUE)
GROUP BY bucket;
```
we were rendering its definition as:
``` 
SELECT bucket,
tx_count,     
total_fee_sat,
total_fee_usd,
stats_fee_sat,
avg_tx_size,  
avg_tx_weight,
high_fee_count
FROM _timescaledb_internal._materialized_hypertable_2;
```
With this PR, we'll render it properly:
```
SELECT …
```
> fix: render timescale views

- projects/extension/tests/upgrade/test_upgrade.py
We install the pgai library inside the extension's docker container via `uv pip install --editable`. Let's make use of that in the upgrade tests. Then, we don't have to install the pgai library and it's dependencies in the extension's venv on the host which mucks things up.
> test: make pgai install work from host or docker

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/__init__.py
- projects/pgai/pgai/vectorizer/processor.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
Move the processing logic from the cli into vectorizer so we can expose it in the library.
Tried to change the least logic possible in moving it over
> chore: refactor processing logic

- projects/pgai/pgai/vectorizer/embeddings.py
Adds:
- 'tokens.total' to 'embeddings.do' span
- 'batch.tokens.total' to 'embeddings.do.embedder.create' span
> chore: add token counts to tracing

- projects/pgai/pgai/vectorizer/processor.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
Usage now becomes e.g.
```
async def lifespan(_app: FastAPI):
processor = Processor(DB_URL)
task = asyncio.create_task(processor.run())
yield
print("Shutting down...")
print("gracefully shutting down processor...")
await processor.request_graceful_shutdown()
try:
result = await asyncio.wait_for(task, timeout=20)
if result is not None:
print("Processor shutdown with exception:", result)
else:
print("Processor shutdown successfully")
except asyncio.TimeoutError:
print("Processor did not shutdown in time, killing it")
print("Shutting down complete")
```
> feat: add graceful shutdown to processor

- projects/pgai/db/sql/incremental/026-change_trigger_definition.sql
- projects/pgai/pgai/data/ai.sql
`raise` has to be inside a `begin` `end` block
> fix syntax error in 026-change_trigger_definition.sql

- README.md
- examples/simple_fastapi_app/with_psycopg.py
- examples/simple_fastapi_app/with_sqlalchemy.py
- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/__init__.py
- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/pgai/vectorizer/worker.py
- projects/pgai/tests/vectorizer/cli/test_vectorizer_core.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
The thread worker rename to Executor.
> chore: rename Processor->Worker

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/semantic_catalog/builder.py
- projects/pgai/pgai/semantic_catalog/gen_sql.py
- projects/pgai/pgai/semantic_catalog/render.py
- projects/pgai/pgai/semantic_catalog/semantic_catalog.py
- projects/pgai/pgai/semantic_catalog/templates/procedure.j2
- projects/pgai/pgai/semantic_catalog/templates/table.j2
- projects/pgai/pgai/semantic_catalog/templates/view.j2
- projects/pgai/pyproject.toml
- projects/pgai/tests/semantic_catalog/data/render_procedures.expected
- projects/pgai/tests/semantic_catalog/data/render_tables.expected
- projects/pgai/tests/semantic_catalog/data/render_views.expected
- projects/pgai/tests/semantic_catalog/test_render.py
- projects/pgai/uv.lock
1. create and load the postgres_air database
```bash
docker run -d --name postgres-air --hostname postgres-air -p 127.0.0.1:5555:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:17
psql -d "postgres://postgres@localhost:5555/postgres" -v ON_ERROR_STOP=1 -f postgres_air_2024.sql
```
2. create a semantic catalog database
```bash
docker pull timescale/timescaledb-ha:pg17
docker run -d --name semantic-catalog --hostname semantic-catalog -p 127.0.0.1:5656:5432 -e POSTGRES_HOST_AUTH_METHOD=trust timescale/timescaledb-ha:pg17
psql -d "postgres://postgres@localhost:5656/postgres" -c "create database semantic_catalog;"
```
3. install pgai into the semantic catalog database
```bash
uv run pgai install -d "postgres://postgres@localhost:5656/semantic_catalog"
```
4. create a new semantic catalog …
> feat: generate sql

- llms.txt
- scripts/generate_llms_txt.py
The script doesn't 100% work anymore because it wasn't build for the world where pgai is just a library but oh well. Better than referencing files that don't exist. We can improve on it later.
> docs: update llms.txt

- projects/pgai/pgai/semantic_catalog/gen_sql.py
The `Diagnostic` object on a `psycopg.Error` contains valuable details on the reason why the query is bad. Send this info  back to the LLM
> feat: provide more context to LLM when EXPLAIN fails

- README.md
change 3.5-turbo model reference to 4o-mini
> docs: use gpt o4-mini instead of of 3.5-turbo in README.md

- .github/workflows/ci.yml
> Revert "ci: validate docker image once merged to main"

- docs/semantic_catalog/README.md
- docs/semantic_catalog/more-questions.md
- docs/semantic_catalog/quickstart-demo-data.md
- docs/semantic_catalog/quickstart-your-data.md
Split quickstart content into focused guides and expanded main README with comprehensive text-to-SQL concepts, implementation details, and architectural diagrams.
> docs: restructure semantic catalog documentation
