- docs/advanced.md
- docs/trigger_moderate.md
- examples/trigger_moderate.sql
I was not sure if we start with an `examples` folder or just adding as docs. Probably generating some mkdocs could also be amazing or deploying the content directly to docs.timescale.com.
Let me know if I should also append the full script.
> Add trigger moderate full example as a doc

- Dockerfile
- test.sh
- test.sql
- tests/anthropic.sql
- tests/cohere.sql
- tests/eval.sql
- tests/ollama.sql
- tests/openai.sql
- `make test` now works whether you are inside or outside the docker container
- tests now better handle errors that cause the `actual` psql variable to be unset
- fail if no tests were run
> Improve testing

- Dockerfile
- Makefile
- build.py
- src/ai/anthropic.py
- src/ai/cohere.py
- src/ai/ollama.py
- src/ai/openai.py
- src/ruff.toml
Adds 4 new make targets:
1. lint-sql - runs pgspot linter against the output SQL for the current version
2. lint-py - runs ruff linter against the python source files
3. lint - runs both lint-sql and lint-py
4. format-py - runs ruff format check against the python source files
Fixes issues found by linters and format check
> Add linting tools

- docs/ollama.md
- Fix typo referencing OpenAI instead of Ollama
> Fix typo referencing OpenAI instead of Ollama

- sql/idempotent/01-openai.sql
- src/ai/anthropic.py
- src/ai/cohere.py
- src/ai/ollama.py
- src/ai/openai.py
- tests/ollama.sql
@avthars not sure whether we want to support this or not.
It would allow someone to use the `openai` functions but point it to [openrouter](https://openrouter.ai/docs/quick-start) or [ollama](https://github.com/ollama/ollama/blob/main/docs/openai.md) instead of openai.
There are actually a number of parameters to creating an openai client that we don't currently support that we may want to consider:
```python
def __init__(
self,
*,
api_key: str | None = None,
organization: str | None = None,
project: str | None = None,
base_url: str | httpx.URL | None = None,
timeout: Union[float, Timeout, None, NotGiven] = NOT_GIVEN,
max_retries: int = DEFAULT_MAX_RETRIES,
default_headers: Mapping[str, str] | None = None,
default_query: Mapping[str, object] | None = None,
http_client: httpx.Client | None …
```
> OpenAI base_url parameter and Ollama OpenAI support

- sql/idempotent/01-openai.sql
- sql/idempotent/02-ollama.sql
- sql/idempotent/04-cohere.sql
Database functions were all volatile. This is not as performant as it could be. This PR changes the volatility of many functions to address this.
- The text generation/chat complete functions were left volatile
- ollama_ps was left volatile since it describes the running state of ollama
- the "list models" were made stable since models can be added/removed at any time
- embed, classify, moderate, etc. were made immutable
> Modify func volatility for performance

- Makefile
- build.py
- sql/ai--0.4.0.sql
I tried to make certain make targets "smarter" (e.g. don't try to remove a docker container if it doesn't exist), but the calls to `docker ps` were hanging in some situations, and it became more annoying than valuable.
> Fix issue with docker ps hanging

- sql/ai--0.4.0.sql
- sql/idempotent/001-openai.sql
- tests/test_openai.py
Current openai_chat_complete function requires choosing the model, submitting the message in a json object, and parsing the json object output. This can feel cumbersome to do.
This openai_chat_complete_simple chooses a default model, only requires the message to be passed as text, and returns the response as text. This should be easier to use, albeit maybe not as powerful.
Future work:
- Consider making the default model an env variable
- Repeat for the other LLMs (Anthropic, Cohere, Ollama)
> Add openai_chat_complete_simple (and tests)

- .github/CODEOWNERS
Just include the entire ts-vector team there.
> Add ts-vector team to CODEOWNERS

- Makefile
- build.py
- src/vectorizer/.dockerignore
- src/vectorizer/Dockerfile
The vectorizer tool can be run in the development container for ease of development and testing. However, we want a separate Docker image for production deployments. This PR adds the image for prod and make targets to aid in all the various build/test tasks.
> Add docker image for vectorizer tool

- build.py
- src/extension/setup.cfg
1. don't install the vectorizer cli tool by default. make it explicit
2. fix setup.cfg so that it's compatible with python 3.10
> build fixes

- tests/contents/test_contents.py
- tests/dump_restore/test_dump_restore.py
- tests/privileges/test_privileges.py
- tests/vectorizer/test_chunking.py
- tests/vectorizer/test_embedding.py
- tests/vectorizer/test_formatting.py
- tests/vectorizer/test_indexing.py
- tests/vectorizer/test_processing.py
- tests/vectorizer/test_scheduling.py
- tests/vectorizer/test_vectorizer.py
i want these tests to run by default unless explicitly disabled. mainly for ci, but I guess it doesn't hurt in general.
these tests do not require any API keys, so they are easy to run by default
when we integrate Alejandro's hoverfly stuff, we can default enable all of them
> feat: make certain tests run by default

- projects/extension/sql/ai--0.4.0.sql
- projects/extension/sql/idempotent/012-vectorizer-api.sql
- projects/extension/tests/dump_restore/after.sql
- projects/extension/tests/dump_restore/init.sql
- projects/extension/tests/privileges/init1.sql
- projects/extension/tests/vectorizer/test_vectorizer.py
we only support automatic index creation if scheduling is enabled. fail if indexing is not none but scheduling is none
> feat: if scheduling is none, indexing must be none

- projects/pgai/Dockerfile
- projects/pgai/pgai/cli.py
- projects/pgai/requirements.txt
- Introduced `--poll-interval` option to specify the wait time before checking for new work after processing all available tasks.
- Added `--once` flag to exit the program after processing all available work in the queue.
Closes [AI-58](https://linear.app/timescale/issue/AI-58/modify-vectorizer-container-to-keep-running-and-log-status)
> feat: add polling mode to vectorizer cli

- docs/vectorizer.md
- docs/vectorizer_guide.md
This is an awesome doc, a few tw suggestions for you to emphasize the workflow in the doc rather than the feature name. 
What I suggest is that we change the name of this guide to vectorizer.md, and the current vectorizer.md to vectorizer-api-reference.md.
> chore: doc review

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/embeddings.py
- projects/pgai/pgai/vectorizer/lambda_handler.py
- projects/pgai/pgai/vectorizer/secrets.py
This PR enables to use any other secret for the OpenAI API Key rather than hardcoded `OPENAI_API_KEY `.
> fix: enable using any key for the OPENAI_API_KEY secret

- projects/pgai/pgai/cli.py
Without being declared as a flag, --once will want to be passed a value (True or False), which is unnecessary.
> cli: --once is a flag

- build.py
- projects/pgai/Dockerfile
- projects/pgai/pgai/__main__.py
- projects/pgai/pgai/cli.py
- projects/pgai/pyproject.toml
Instead of the cli running directly the vectorizer worker, the worker has been moved to its own command. The entry point has been rename from vectorizer to pgai.
This will allow us to add other commands seamlessly in the future, without having to introduce breaking changes or multiple scripts.
The workflow will look like this:
```
$ pip install pgai
$ pgai --help
Usage: pgai [OPTIONS] COMMAND [ARGS]...
Options:
--version  Show the version and exit.
--help  Show this message and exit.
Commands:
vectorizer
$ python -m pgai vectorizer --help
Usage: python -m pgai vectorizer [OPTIONS] COMMAND [ARGS]...
Options:
--version  Show the version and exit.
--help     Show this message and exit.
Commands:
worker
$ pgai vectorizer worker --help
Usage: pgai vectorizer worker [OPTIONS]
Options:
--version …
```
> feat: use commands for scoping the cli

- .gitignore
- projects/extension/sql/idempotent/999-privileges.sql
- projects/extension/tests/upgrade/snapshot.sql
- projects/extension/tests/upgrade/test_upgrade.py
The grant_ai_usage function was inserting into _secret_permissions without checking whether the row already exists. This fails the primary key constraint and causes extension version upgrades to fail.
Added tests to check that the extension can be upgraded. We upgrade through each step in the upgrade path then snapshot the results. Then we create the extension on the latest version and snapshot it. The snapshots should be equal.
> Bug fix and Upgrade Tests

- projects/extension/Dockerfile
- projects/extension/build.py
the vast majority of the time spend in CI is on building the timescaledb and pgvectorscale extensions. let's avoid that
> build: don't build timescaledb or pgvectorscale from scratch

- projects/extension/sql/idempotent/013-vectorizer-api.sql
I just found an error showing the following message:
```
ERROR:  an object named public.public already exists. specify an alternate destination or target_table explicitly 
```
Digging the code I see the table name was missing and the schema was repeated.
1. create a table
2. create a vectorizer based on the table
3. drop the table
4. `truncate ai.vectorizer cascade`;
5. repeat step 1 and then step 2 will fail.
> Fix interpolation call: target_schema to target_name

- docs/vectorizer-quick-start.md
- docs/vectorizer-worker.md
`docker-compose` only works on Compose v1.
For Compose v2, which was released 4 years ago, the command should be `docker compose`.
> docs: update docker-compose command

- projects/extension/Makefile
- projects/extension/build.py
- projects/extension/sql/incremental/frozen.txt
Incremental SQL files are database migrations. They are tracked in the `ai.migration` table. They are intended to be executed exactly once and in a deterministic order. For this reason, once we have shipped a version of the extension, all incremental files that existed as of that version must not be changed. They are frozen. This PR enforces this policy.
> build: disallow changes to incremental files that have shipped

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/contents/output.expected
- projects/extension/tests/privileges/function.expected
- projects/extension/tests/vectorizer/test_vectorizer.py
Adds an event trigger to detect when a source, queue, or target table associated with a vectorizer is dropped. The event trigger calls ai.drop_vectorizer to clean up the mess.
a vectorizer has:
1. source table
2. queue table
3. target table
4. view
5. trigger
6. func backing the trigger
7. row in the ai.vectorizer table
- a user could drop/rename/move any or all of 1-6
- a user could delete the row from the ai.vectorizer table
doing either of those *could royally screw up the vectorizer
- trying to handle alter table... rename... is basically impossible without writing C
- trying to handle alter table... set schema... is basically impossible without writing C
so i'm focussed on drop table
- a superuser can drop anything
- the owner of a table can drop a table
- the owner of a schema can …
> add event triggers to handle table changes

- projects/extension/Dockerfile
- projects/pgai/tests/vectorizer/conftest.py
Change pgai testcontainer to build the extension and copy the extension code to a timescaledb-ha container.
This will make CI run the pgai python library against the latest changes made to the extension, and surface breaking changes sooner.
> chore: run pgai tests against extension from source

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/tests/vectorizer/test_vectorizer.py
Currently, if the source table has had a column dropped, `create_vectorizer` will fail. This PR fixes this bug.
> fix: handle dropped columns when creating vectorizers

- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/contents/output.expected
Currently, if you call the `ai.vectorizer_status` view and you do not have SELECT privs on one or more queue tables, the view will fail. This PR prevents the view from failing by returning 0 for queue pending for these vectorizers.
> fix: prevent vectorizer status view from failing if missing privs

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/incremental/003-vec-storage.sql
- projects/extension/tests/vectorizer/test_vectorizer.py
Based on prior benchmarking, using storage plain (rather than extended/external) for vector columns performs much better. Unfortunately, it is difficult to determine whether a target table row will definitively fit on a single postgres page. Therefore, we will assign storage main to the vector columns, which will keep them inline unless they won't fit and toast otherwise.
NOTE: We will set storage to main for existing vectorizers (unless they have been already manually set to main or plain), but this will not take effect until a table rewrite happens. This can be done with `CLUSTER` or `VACUUM FULL` and may take a while depending on the size of the table.
>The TOAST management code recognizes four different strategies for storing TOAST-able columns on disk:
>
>PLAIN prevents either …
> perf: vector columns use storage main

- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/contents/output.expected
If a vectorizer has no queue table, or the user does not have select privileges on the queue table we will now return null for the pending_items column in the vectorizer_status view.
> fix: vectorizer_status return null if no queue or missing privs

- docs/vectorizer-api-reference.md
- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/sql/incremental/005-vectorizer-queue-pending.sql
- projects/extension/tests/contents/output.expected
- projects/extension/tests/privileges/function.expected
- projects/extension/tests/vectorizer/test_vectorizer.py
Previously, we counted every row in the queue in `ai.vectorizer_queue_pending`, which could be very slow for large queues. Now, we limit 10,001 by default and add an `exact_count` bool parameter, which can be used to get an exact count if desired.
> perf!: don't do an exact count by default in vectorizer_queue_pending

- projects/pgai/pgai/cli.py
- projects/pgai/tests/vectorizer/conftest.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
- projects/pgai/tests/vectorizer/test_vectorizer_cli.py
The vectorizer worker (running in continuous mode) now checks for the presence of new vectorizers on each pass through its work loop. This ensures that it processes vectorizers which are added after the worker starts.
> fix: make vectorizer worker poll for new vectorizers

- projects/pgai/tests/vectorizer/conftest.py
- projects/pgai/tests/vectorizer/test_vectorizer_cli.py
In 12c17809ec235d759e37eaa0898ea3274fea6319 we made tests less fragile by giving each test class its own fresh container, which also made the tests run a bit slower.
This change reuses the same container for all tests, but creates a new database for each test, achieving the same isolation, with low overhead.
> chore: a new database for each test

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/contents/output.expected
- projects/extension/tests/privileges/function.expected
- projects/extension/tests/vectorizer/test_vectorizer.py
Adds entries into pg_depend such that when you `drop table <source-table> cascade` or `drop table <target-table> cascade` will also drop the queue table for vectorizers, and when you `drop table <source-table> cascade` it will also drop the target table too.
> feat: drop cascade for vectorizers

- .github/workflows/ci.yml
We were specifying that CI should be run on push, and on pull_request, this end up running jobs twice.
Push is the more useful of the two, because it means that you don't have to wait for a PR to be opened for the build to run against the changes.
> chore: only run CI on push

- projects/extension/Dockerfile
This removes our dependency on the timescale/timescaledb-ha docker image. The debian packages are released first, and this allows us to test new versions sooner.
> build: use deb pkgs for timescaledb and pgvectorscale

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/tests/privileges/test_privileges.py
In f68e73ac we added support for cascading the source/target table drop to the queue and other dependent objects. In adding this, we added a security definer function which asserts that the owner of the source table is calling the security definer function.
Due to how security definer functions work with `current_user`, the ownership check opted to use `session_user` to check ownership. This is problematic because in connections which use `SET ROLE`, the `session_user` may not be the same as `current_user`.
This commit relaxes the ownership check to check whether the current
user is a member of the role that owns the source table.
> fix: allow members of source table to create vectorizer

- .github/workflows/release-please.yml
In a multirepo setup, the release-please git tag contains the project prefix (`pgai-`). We were using this git tag as the docker container tag. This change strips the `pgai-` prefix from the git tag when generating the docker container tag. The resulting image name is: `timescale/pgai-vectorizer-worker:v<version>`.
Also overrides the description and title labels, which were derived from the github repository description and name respectively, so were not specific to the vectorizer worker.
> chore: fix vectorizer worker docker labels and version

- .github/ISSUE_TEMPLATE/config.yml
I've clicked on the link and got an error message from discord because I hadn't joined the server. The new link is the one from the readme.
> fix: discord server link in issue template

- CONTRIBUTING.md
This pull request improves the contributing guideline by introducing a structured framework for proposing and implementing changes to our source code.
The RFC process ensures that significant changes are proposed, discussed, and implemented systematically, reducing miscommunication and aligning the community efforts.
Strongly inspired by [AsyncAPI contributing guidelines](https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md).
> docs: add RFC Stages to our contributing guidelines

- docs/anthropic.md
- examples/anonymize_entities.sql
- examples/extract_entities.sql
- examples/summarize_article.sql
- projects/extension/sql/idempotent/003-anthropic.sql
A minimal example of how to use tool_use.
<details>
<summary>The original function gives me this error</summary>
```
ERROR:  anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'tools: Input should be a valid list'}}
CONTEXT:  Traceback (most recent call last):
PL/Python function "anthropic_generate", line 42, in <module>
message = client.messages.create(model=_model, messages=_messages_1, max_tokens=_max_tokens, **args)
PL/Python function "anthropic_generate", line 276, in wrapper
PL/Python function "anthropic_generate", line 903, in create
PL/Python function "anthropic_generate", line 1248, in post
PL/Python function "anthropic_generate", line 930, in request
PL/Python function "anthropic_generate", line 1028, in _request …
```
> Use tools with anthropic_generate (example type tool_use)

- .github/workflows/ci.yml
- DEVELOPMENT.md
- projects/extension/build.py
- projects/extension/tests/test_anthropic.py
- projects/extension/tests/test_cohere.py
- projects/extension/tests/test_ollama.py
- projects/extension/tests/test_openai.py
- projects/extension/tests/test_voyageai.py
I replaced the ENABLE_ flags for each API provider with simply checking if a key is present. I think this makes more sense so you don't have to provide both env vars?
I also added a download fixture to the ollama tests so that the necessary models are downloaded during the test runs. This is quite slow, but I guess we can add caching later.
Other than that this was quite straight forward. Only issue is that voyageai already hits rate limits with my free key now.
> chore: enable extension tests in ci

- projects/extension/build.py
The `--network host` flag is not supported on macos and Windows (unless a beta flag is enabled). Let's make the dev environment work out-of-the-box. If we turn on `--network host`, the `-p 127.0.0.1:5432:5432` flag is ignored, and then you cannot connect to the database from outside the container. This breaks the dev/test experience for non-linux users.
>The host networking driver only works on Linux hosts, but is available as a beta feature on Docker Desktop version 4.29 and later for Mac, Windows, and Linux. To enable this feature, navigate to the Resources tab in Settings, and then under Network select Enable host networking.
https://docs.docker.com/engine/network/tutorials/host/
> fix: host networking is not supported on mac

- docs/vectorizer-quick-start-voyage.md
This looks fine in pycharm but not on github. Good to know that there is a little difference between the markdown renderers.
> docs: fix formatting of table for voyageai

- docs/vectorizer-quick-start-openai.md
- docs/vectorizer-quick-start-voyage.md
- docs/vectorizer-quick-start.md
- docs/vectorizer-worker.md
In aabbc681 we corrected the volume path for the database data volume. If the 'data' directly does not already exist then this fails on both Mac and Linux because the directory is created as root and the postgres user in the container doesn't have permissions to initdb.
Switching to a named volume solves these problems, and prevents us polluting `pwd` with the data dir.
> docs: use named volumes in quickstart guides

- projects/pgai/pyproject.toml
- projects/pgai/uv.lock
The build started failing with the following error message:
```
Checking ./dist/pgai-0.3.0-py3-none-any.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name,
Version.
Make sure the distribution includes the files where those fields are
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,
2.0, 2.1, 2.2, 2.3.
```
This error comes from `twine check dist/*`. It is caused by the fact that `hatchling`, which we use to build wheels, released a new version which bumped the `Metadata-Version` field to `2.4`, and twine/pkginfo aren't able to process this version.
By pinning `hatchling` to 1.26.3, the previous release, we solve this immediate problem, and avoid new breakage from future hatchling releases.
> chore: fix broken pgai build by pinning hatchling

- projects/extension/Dockerfile
- projects/extension/build.py
- projects/extension/requirements-test.txt
We would like to support uv in an opt-in fashion. The `build.py install` now uses uv if it is available, otherwise falling back to pip. To use uv, we now install it in our dev containers.
> chore: support uv in extension install, use for dev

- projects/extension/build.py
We install the dependencies for an extension version in a specific path for that version alone. When one of our plpython3u functions is called, we set up the python path to include these dependencies.
For the very first extension releases, we didn't do it this way. Instead, the dependencies were installed into the system python's path. As a result, we were inadvertently using _both_ packages installed for the system python, and the packages installed for the specific extension version. When the same package is installed in both, the system python version is chosen first. This breaks Python's assumptions about dependency resolution, and can break installed packages.
This change removes the system python dependencies from the python path, so only the actual dependencies we wanted are …
> fix: exclude python system packages for versioned extension

- .github/workflows/ci.yml
- projects/extension/build.py
Running the script under Python 3.13, I get:
```
/Users/mpeveler/code/timescale/pgai/projects/extension/./build.py:86: DeprecationWarning: 'maxsplit' is passed as positional argument
parts = re.split(r"[.-]", version, 4)
```
which this PR resolves. The deprecation warning was added in Python 3.13, where at some future version of Python, `maxsplit` will be required to be passed as a keyword-only argument.
> fix: deprecation warning on re.split

- docs/vectorizer-api-reference.md
- docs/vectorizer-quick-start.md
We actually don't allow l2 distance according to the code:
https://github.com/timescale/pgai/blob/main/projects/extension/sql/ai--0.6.0.sql#L2112 (although it would probably work if we'd change that)
The vectorizer quickstart is ollama focused on openai not sure how that snuck in there.
> docs: remove openai mention, fix opclasses in hnsw index

- projects/pgai/tests/vectorizer/conftest.py
- projects/pgai/tests/vectorizer/test_vectorizer_cli.py
This PR spawns a new `ollama/ollama:latest` container through testcontainers when a test requires an ollama server to be up.
As a mechanism to override this behavior, the container won't be used if a `OLLAMA_HOST` env var is found, using the value of it instead.
Open to better alternatives.
> test: spawn the ollama container through testcontainers

- projects/extension/sql/idempotent/905-text-to-sql.sql
PR modifies the system prompt that's used for `text_to_sql` to include not wrapping the returned query in markdown as `ai.text_to_sql_openai` often would. With this change, I found that both `text_to_sql_anthropic` and `ai.text_to_sql_openai` just return the SQL query and nothing else.
> fix: openai wrapping text-to-sql query in markdown

- projects/pgai/pyproject.toml
- projects/pgai/tests/vectorizer/extensions/conftest.py
- projects/pgai/uv.lock
PR replaces usage of `psycopg2` with `psycopg` for the sqlalchemy tests that were added in #265, as we already were installing `psycopg` for other tests, and that installing `psycopg2` can be a bit annoying for folks on macOS (see https://github.com/psycopg/psycopg2/issues/1200 as an example).
> test: use psycopg over psycopg2 for sqlalchemy tests

- projects/pgai/pyproject.toml
PR registers the custom `pytest.mark.postgres_params` mark (per [pytest docs](https://docs.pytest.org/en/stable/how-to/mark.html)) so that should no longer see the following warning when running the pgai tests:
```
=============================================== warnings summary ===============================================
tests/vectorizer/test_vectorizer_cli.py:320
/Users/mpeveler/code/timescale/pgai/projects/pgai/tests/vectorizer/test_vectorizer_cli.py:320: PytestUnknownMarkWarning: Unknown pytest.mark.postgres_params - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.postgres_params(load_openai_key=False)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> chore: register postgres_params custom pytest.mark

- DEVELOPMENT.md
- projects/extension/build.py
- projects/extension/justfile
PR adds a `just ext docker-start` cmd which mirrors the `just ext docker-stop` command. I've got a couple of projects that use postgres and all expose the `5432` port on the host, and so was using the `just ext docker-stop` when I switched projects, and was then annoyed when there wasn't a matching `just ext docker-start` command, and having to result to bare docker commands.
> feat: add just ext docker-start cmd

- projects/extension/build.py
pgspot had a [bug](https://github.com/timescale/pgspot/pull/213) that caused our lint step to fail on valid plpgsql code. That bug has been [fixed](https://github.com/timescale/pgspot/pull/213), so this PR re-enables the linting.
> chore: re-enable pgspot linting now that pgspot bug is fixed

- projects/pgai/pgai/vectorizer/chunking.py
- projects/pgai/tests/vectorizer/test_vectorizer_cli.py
The chunking configuration takes a 'chunk_column' parameter, which determines which column of the source row is chunked.
This commit treats a null entry as being equivalent to the empty string, and no embeddings are generated.
Fixes #334
> fix: handle 'null' value in chunking 'chunk_column'

- projects/extension/pyproject.toml
uv caches info about local packages you are installing unless some special files are touched. This prevents changes to local files being installed and thus makes the development workflow broken.
Turn off caching on the local package
> chore: fix uv caching

- projects/pgai/pgai/cli.py
When debugging #334 the first thing I needed was a backtrace of the reported error. I added this code to print the backtrace to the debug logs. The resulting log looks as follows:
```
2025-01-06 14:51:23 [error    ] unexpected error: expected string or bytes-like object
2025-01-06 14:51:23 [debug    ] Traceback (most recent call last):
2025-01-06 14:51:23 [debug    ]   File "/home/james/workspace/pgai/projects/pgai/pgai/cli.py", line 319, in vectorizer_worker
2025-01-06 14:51:23 [debug    ]     run_vectorizer(
2025-01-06 14:51:23 [debug    ]   File "/home/james/workspace/pgai/projects/pgai/pgai/cli.py", line 153, in run_vectorizer
2025-01-06 14:51:23 [debug    ]     results = event_loop.run_until_complete(
2025-01-06 14:51:23 [debug    ]   File …
```
> feat: print unexpected error traceback in debug logs

- .github/workflows/ci.yml
- projects/pgai/justfile
- Updated the `just pgai install` to include the `--all-extras` flag.
- Modified the command for installing dependencies in GH actions to use `just pgai install`.
> ci: install all dependencies through just pgai install

- docs/vectorizer-quick-start-ollama.md
I thought maybe we can symlink this, but github doesn't seem to resolve those. E.g. when you click on the file you don't end up on the linked md file.
Alternatively leave this as an accepted drawback of using github for docs. If we ever host the pgai docs on a real docs website (or merge them into timescales docs) we can revisit this.
I don't feel strongly either way.
> docs: add vectorizer-quick-start-ollama.md file with link

- docs/python-integration.md
- projects/pgai/pgai/sqlalchemy/__init__.py
- projects/pgai/tests/vectorizer/cassettes/test_parent_joined_loading.yaml
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_composite_primary.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_large_embeddings.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_lazy_strategies.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_relationship.py
- projects/pgai/tests/vectorizer/extensions/utils.py
I am fixing two quite annoying issues with the SQLAlchemy integration in this PR:
1. It wasn't possible to have the same field name configured on two different entities. So you can't have `content_embeddings` twice, because the name was colliding in the Mapper configuration. So I changed the dynamically generated Model name to contain the parent Model.
2. The way we were configuring the relationship into the other direction via `backref` was somewhat lazily evaluated and is also no longer recommended by SQLAlchemy. It's considered "legacy". I changed it with some back and forth to be simply two relationships in both directions and added a `parent_kwargs` field that allows to configure the relationship into the reverse direction.
> fix: two usability issues with sqlalchemy

- projects/pgai/pgai/sqlalchemy/__init__.py
- projects/pgai/tests/vectorizer/extensions/test_inheritance.py
I was using the direct base class of the model class not really considering that there could be models in between. This PR fixes it and should be somewhat resilient even to legacy ways of using sqlalchemy (although I think they are not very popular)
> fix: vectorizer_relationship for sqlalchemy models with mixins or inheritance

- .github/workflows/ci.yml
Restricts the concurrency of the ci workflow - aborting existing jobs on the same pull request.
> chore: restrict concurrency of ci workflow

- projects/extension/sql/idempotent/905-text-to-sql.sql
Fixes a bug where doing `ai._table_def` will return `null` if the referenced oid does not have any indexes. To reproduce, do:
```sql
CREATE TABLE public.city (
city_name text,
population bigint,
country_name text DEFAULT ''::text NOT NULL,
state_name text
);
SELECT ai._table_def('public.city'::regclass::oid) IS NULL
```
where the second query will return `true`.
> fix: ai._table_def returning null if no indexes

- .github/workflows/commit-lint.yml
- docs/vectorizer-quick-start.md
We were not retrieving the model on this example, fix the vectorizer-quick-start.
Also limit results to have better accuracy on results.
Finally add concurrency to prevent several subsequent commits
to run CI multiple times.
> docs: fix quickstart, retrieve ollama model

- docs/vectorizer-quick-start-openai.md
- docs/vectorizer-quick-start-voyage.md
- docs/vectorizer-quick-start.md
- docs/vectorizer-worker.md
- examples/evaluations/ollama_vectorizer/compose.yaml
- examples/evaluations/voyage_vectorizer/compose.yaml
- examples/finding_best_open_source_embedding_model/compose.yaml
We were using a pinned version for the vectorizer worker docker image in our docker compose examples. As a result, the behaviour of the docker compose examples didn't reflect our documentations.
This commit switches all usages of `timescale/pgai-vectorizer-worker` to use the `latest` tag.
> docs: switch to 'latest' tag for vectorizer worker docker image

- projects/extension/ai/load_dataset.py
- projects/extension/tests/test_load_dataset.py
Previously, struct fields weren't handled correctly.
Now, we flatten the structures to handle them better.
Fixes #328
> fix: load_datasets to handle structs

- justfile
- projects/extension/build.py
- projects/extension/justfile
Pre-release versions of the pgai extension do not have a defined upgrade
path to released versions. Installing these versions could leave
databases in a problematic state that cannot be cleanly upgraded.
This change prevents accidental installation of development builds by
directing users to official releases, while still allowing intentional
installation of pre-release versions via the explicit build-install
command.
> feat: add warning when trying to install pre-release version

- projects/extension/tests/text_to_sql/test_dump_restore.py
- projects/extension/tests/text_to_sql/test_text_to_sql.py
- When prepping for a release, we change [the current version](https://github.com/timescale/pgai/blob/main/projects/extension/build.py#L43) to a release version (e.g. `0.7.0`) and remove any pre-release tag (e.g. `0.7.0-dev`). 
- Then, we build the output SQL and check it in.
- When we build output SQL, if we are building a release version, we omit any code that is behind a feature flag
- If feature flagged code has tests, then those tests need to detect that this is a release build and be skipped. If they attempt to run, the code they are testing will not exist in the database.
This PR modifies the text-to-sql tests to detect whether or not the current version is a release build. If it is a release build, the tests are skipped.
> test: do not run pre-release tests on a release build

- projects/extension/build.py
- projects/extension/justfile
When prepping for a release, we need to 
1. build and commit the output sql
2. update the __version__ in __init__.py
This new `just build-release` command will do those steps without installing anything into the system.
We have a `just format-py` to check the python formatting using ruff. This adds a `just reformat-py` which will run ruff to correct the formatting automatically.
> Add `build-release` and `reformat-py` just commands

- .github/ISSUE_TEMPLATE/config.yml
I believe we should not be that restrictive with users that want to create an issue and allow them to create blank issues if they don't find a template that fits with their needs.
> chore: allow the creation of blank issues in this repo

- DEVELOPMENT.md
- justfile
- projects/extension/DEVELOPMENT.md
- projects/pgai/DEVELOPMENT.md
This PR improves the Development documentation by:
- It splits current `DEVELOPMENT.md` file into 3 files:
1. Moves all guidelines related to the extension to `projects/extension/DEVELOPMENT.md`.
2. Moves all guidelines related to the pgai library to `projects/pgai/DEVELOPMENT.md`. 
3. Keeps the current root file as index, adding links to each of the files listed above.
- It improves (I hope it does) the `DEVELOPMENT.md` root file by making it a bit more comprehensible and by adding missing context.
Additionally, I fixed the `just install-commit-hook` command as it was failing. I didn't move that change into its own single PR because the change is sooo small, but if you believe it should be done in that way, just mention it, I'm fine.
> docs(dev): improve and split DEVELOPMENT.md

- projects/extension/ai/anthropic.py
- projects/extension/sql/idempotent/003-anthropic.sql
- projects/extension/tests/contents/output16.expected
- projects/extension/tests/contents/output17.expected
- projects/extension/tests/privileges/function.expected
- projects/extension/tests/test_anthropic.py
PR implements the `ai.anthropic_list_models` function, which currently returns columns `(id, name, created)` which gives:
```
test=# SELECT ai.anthropic_list_models();
anthropic_list_models
---------------------------------------------------------------------------------
(claude-3-5-sonnet-20241022,"Claude 3.5 Sonnet (New)","2024-10-22 00:00:00+00")
(claude-3-5-haiku-20241022,"Claude 3.5 Haiku","2024-10-22 00:00:00+00")
(claude-3-5-sonnet-20240620,"Claude 3.5 Sonnet (Old)","2024-06-20 00:00:00+00")
(claude-3-haiku-20240307,"Claude 3 Haiku","2024-03-07 00:00:00+00")
(claude-3-opus-20240229,"Claude 3 Opus","2024-02-29 00:00:00+00")
(claude-3-sonnet-20240229,"Claude 3 Sonnet","2024-02-29 00:00:00+00")
(claude-2.1,"Claude 2.1","2023-11-21 00:00:00+00")
(claude-2.0,"Claude 2.0","2023-07-11 …
```
> feat: add ai.anthropic_list_models

- projects/extension/build.py
While developing, sometimes I want to implement something a few different ways and compare. The easiest thing to do is to keep each version in a separate SQL file. But I can only have one at a time built and tested.
I don't want to
1. move the SQL file to another directory - this is a pain and I still want to be able to look at the file in my editor in the context of the project
2. comment out the entire body of the SQL - also a pain and destroys and IDE niceties
3. delete the file - I haven't decided to discard the work
What I want is an easy way to temporarily ignore a SQL file while I'm developing.
This PR allows you to rename a SQL file to add an 'x' prefix to tell the build to ignore the file.
> build: ignore sql files with 'x' prefix

- docs/vectorizer-quick-start-openai.md
- docs/vectorizer-worker.md
Don't merge this before the next vectorizer-worker release!
> docs: adapt docs for optional OPENAI_API_KEY

- projects/pgai/pgai/vectorizer/embedders/openai.py
- projects/pgai/pgai/vectorizer/embeddings.py
At this moment, we are tokenizing the chunks before being sent to OpenAI embedding API. The way that's done is through matching a tokenizer with the given OpenAI model thanks to tiktoken. See [here](https://github.com/timescale/pgai/blob/main/projects/pgai/pgai/vectorizer/embedders/openai.py#L203-L205).
That works because tiktoken has a map of `openai_model => tokenizer`.  
Notice that **is only compatible with OpenAI models**.
This PR allows to skip tokenization whenever we are not able to find a tokenizer for a given model. 
Why this is needed? Because two reasons:
1. Since tiktoken is only compatible with OpenAI models, the call made to match a non-openai model with a tokenizer will always fail.
2. Not all LLM providers accept tokenized input but rather just plain text.
That, among the …
> feat(vectorizer): disable OpenAI tokenization when a model does not have a tokenizer match

- projects/pgai/tests/vectorizer/extensions/test_inheritance.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_composite_primary.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_large_embeddings.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_lazy_strategies.py
- projects/pgai/tests/vectorizer/extensions/test_sqlalchemy_relationship.py
- projects/pgai/tests/vectorizer/extensions/utils.py
- projects/pgai/tests/vectorizer/test_vectorizer_cli.py
- projects/pgai/tests/vectorizer/utils.py
- projects/pgai/uv.lock
Refactors the vectorizer test suite to be more easily readable by:
- Removing nested test_params fixture (num_items, concurrency, batch_size, chunking, formatting) in favor of direct parameters that are then passed to setup functions
- Creating dedicated configuration functions (configure_openai_vectorizer, configure_ollama_vectorizer, etc.) to replace the fixtures
- Using a common `run_vectorizer_worker` helper function standardizing CLI invocation
I also want to split the file up, but wondering how and if I should do that separately.
> chore: get rid of nested parametrization in vectorizer tests

- docs/vectorizer-api-reference.md
- projects/extension/DEVELOPMENT.md
- projects/extension/sql/idempotent/013-vectorizer-api.sql
- projects/extension/sql/incremental/012-add-vectorizer-disabled-column.sql
- projects/extension/tests/contents/output16.expected
- projects/extension/tests/contents/output17.expected
- projects/extension/tests/text_to_sql/snapshot-catalog.expected
- projects/extension/tests/vectorizer/test_vectorizer.py
- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/features/__init__.py
- projects/pgai/pgai/vectorizer/features/features.py
- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/tests/vectorizer/cassettes/test_disabled_vectorizer_is_backwards_compatible.yaml
- projects/pgai/tests/vectorizer/cassettes/test_disabled_vectorizer_is_skipped_before_next_batch.yaml
- projects/pgai/tests/vectorizer/cli/test_openai_vectorizer.py
- projects/pgai/tests/vectorizer/cli/test_vectorizer_core.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
Add ability to enable/disable vectorizers using ai.enable_vectorizer_schedule
and ai.disable_vectorizer_schedule functions. This applies to vectorizers
configured with ai.scheduling_none that use polling-based workers.
Key changes:
- Add disabled column to ai.vectorizer table
- Expose disabled status through ai.vectorizer_status view
- Add checks in Vectorizer Worker to stop processing when disabled
- Improve stopping behavior for ai.scheduling_timescaledb vectorizers
- Add Features class to manage version-dependent functionality
The Vectorizer Worker now checks disabled status before processing each
batch. Disabled vectorizers (both ai.scheduling_none and
ai.scheduling_timescaledb) exit after completing their current batch,
improving on previous behavior where timescaledb vectorizers …
> feat: pause/resume vectorizer

- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
This is non-production, feature-flagged code. Adds support for ollama to text-to-sql. It "works" in the sense that the code does what it's supposed to do, but I haven't gotten an LLM to respond with the correct answer yet. I'm guessing more prompt engineering is needed. But I need to merge this to be able to work on some other refactoring.
> feat(text_to_sql): add ollama support for text-to-sql

- projects/pgai/pgai/sqlalchemy/__init__.py
Fixes #406 
Functionally this doesn't change anything. It just makes it so that if you would somehow attach an embedding to a different parent entity the `.parent` is correctly changed as well. However I don't see this as a valid use-case since the vectorizer is in charge of keeping the embeddings in sync. Therefore I didn't write a test for this, and just added the line to remove the warning by sqlalchemy in the log.
> fix: remove sqlalchemy warning about conflicts

- docs/litellm.md
- docs/vectorizer-api-reference.md
- document ai.litellm_embed()
- clarify huggingface vectorizer
> Improve LiteLLM docs

- projects/extension/tests/test_cohere.py
Cohere recently changed their classify API to require using a pre-trained model [1]. We don't have a pretrained model, and until we decide to make one for these tests, we'll skip them.
[1]: https://docs.cohere.com/changelog/classify-default-model-deprecation
> chore: skip cohere classify tests

- docs/install_from_source.md
The pgai extension install needs to write to system-owned paths, including `/usr/local/lib`, and the postgres extension path, typically `/usr/share/postgresql/<pg version>/extension`.
> docs: pgai extension install requires sudo

- .github/workflows/ci.yml
- projects/extension/DEVELOPMENT.md
- projects/extension/build.py
- projects/extension/justfile
Running `python3 build.py install` would install all versions of the extension (and their python dependencies).
This commit changes this behaviour to only install the sql scripts (including upgrade paths) and python dependencies for the current version of the extension.
For backwards compatibility, use `build.py install all`, which activates the old behaviour.
> feat!: only install current extension version

- projects/extension/build.py
Now that we've dropped the pre-0.4.0 versions, we no longer have a
concrete _need_ for the path hack that we introduced. Nonetheless it
seems cleaner to ensure that things don't mysteriously break because our
dependencies are being overridden by system-level packages.
> chore: re-justify path hack after dropping pre-0.4.0

- README.md
> docs: change readme header to use links instead of images

- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
- projects/extension/sql/idempotent/909-text-to-sql-cohere.sql
PR adds a new tool to `ai.text_to_sql_openai` and `ai.text_to_sql_anthropic` to allow the LLM to fetch a sample of a table if it thinks it needs this context.
I've found that it doesn't seem to ever call this tool, but that can be improved/fixed in a follow-up PR.
This PR is built off #415, so will want to merge that one before merging this one.
> feat: add table sample tool to text-to-sql

- projects/extension/ai/semantic_catalog.py
PR fixes calling the `generate` functions with `openai` provider, where I was mistakenly passing `tool_choice` as a `jsonb` object, where it should have been a `text` value.
> fix: calling generate functions with openai

- projects/extension/DEVELOPMENT.md
- projects/extension/justfile
More often than not, when working on the extension, you are solely working on SQL and not modifying any Python. In this mode, you want to (re)install just the SQL files because it's practically instantaneous. You don't really want to bother reinstalling they Python bits, because 1. you didn't change it 2. it's substantially slower than installing the SQL.
`just install-sql` recently changed to only install the current version. This is fine, except that the upgrade tests will fail unless ALL the SQL versions are installed.
This PR adds `just install-sql-all` to give us the original behavior.
> build(extension): add a 'just install-sql-all' command

- projects/pgai/uv.lock
We recently [commited](https://github.com/timescale/pgai/pull/394#discussion_r1930412278) a uv.lock 
without pgai version specified, which broke uv proper functioning, possibly due to a discrepancy in the
uv version used.
> fix: readd version to uv lock

- projects/pgai/uv.lock
Reverts timescale/pgai#463
Not needed when using last versions of `uv`.
> Revert pgai version inclusion in uv.lock

- projects/pgai/tests/vectorizer/cli/test_vectorizer_document.py
Basically the test will fail for anyone who has a `~/.aws/credentials` file; boto will default to those credentials if they exist.
> test: fix test_simple_document_embedding_s3_no_credentials

- projects/extension/ai/semantic_catalog.py
- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
PR fixes the types of the arguments that were being passed to the `ai.render_sample` function by the `request_table_sample`. To help force the LLM to call the tool to validate the fix, I made the following change to the prompt:
```diff
diff --git a/projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql b/projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
index c24f228..240f9ef 100644
--- a/projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
+++ b/projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
@@ -14,6 +14,7 @@ as $func$
( E'\n'
, $$Below are descriptions of database objects and examples of SQL statements that are meant to give context to a user's question.$$
, $$Analyze the context provided. Identify the elements that are relevant to the …
```
> fix: argument types to ai.render_sample tool

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/idempotent/013-loading.sql
- projects/extension/sql/idempotent/014-parsing.sql
- projects/extension/sql/incremental/017-migrate-vectorizer-queue-tables.sql
- projects/extension/tests/upgrade/test_upgrade.py
- projects/extension/tests/vectorizer/test_vectorizer.py
- projects/pgai/pgai/vectorizer/vectorizer.py
As agreed in the design of the s3 document support, we're including retries and retry_after fields in the queue tables generated for each vectorizer.
Also add a couple of minor changes, rename func used in upgrades, and of vars of the loading migration.
> feat: support queue item retries 

- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
PR updates the tool description for `request_table_sample` that it requires a fully qualified `schema.name` to be passed in, which fixes an error where if it omits the schema, then the `::regclass` cast fails due to the `search_path` not including `public` on the function.
I think it'd be good to do this, in addition to potential search path updates that @jgpruitt is working for the potential case of multi-schema DB setups that people are working over.
> fix(text-to-sql): specify need fully qualified name for sample

- projects/extension/tests/test_openai.py
The test_openai_chat_complete_with_tokens_limitation_on_reasoning_models test is failing randomly. Sometimes the LLM returns content when it is stopped for length reasons. Sometimes it doesn't. Drop the assertion.
> test(openai): do not check content length when stopped for max tokens

- projects/extension/sql/idempotent/905-semantic-catalog-render.sql
- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
- projects/extension/sql/idempotent/909-text-to-sql-cohere.sql
- prompt engineering stuff mostly with openai
- minor bug fixes
> chore(text_to_sql): various prompt eng tweaks and minor fixes

- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
- projects/extension/sql/idempotent/909-text-to-sql-cohere.sql
Now, allow the user to pass "extra" prompt content as a text parameter. Previously, we were using a regprocedure to allow customization, but this is a PITA to use.
The new approach also makes it easy to have different prompts for each provider
> chore(text_to_sql): replace user prompt renderer w/ simple text param

- projects/pgai/pgai/vectorizer/vectorizer.py
Previously exceptions in self.vectorizer.config.embedding.setup() were not recorded in the db.
This PR catches exceptions one stack higher to catch more of them.
> fix: record exceptions in embedding.setup()

- projects/extension/ai/semantic_catalog.py
- projects/extension/sql/idempotent/905-semantic-catalog-render.sql
- projects/extension/sql/idempotent/906-text-to-sql-anthropic.sql
- projects/extension/sql/idempotent/907-text-to-sql-ollama.sql
- projects/extension/sql/idempotent/908-text-to-sql-openai.sql
- projects/extension/sql/idempotent/909-text-to-sql-cohere.sql
- projects/extension/sql/idempotent/910-text-to-sql.sql
Adds a func to resolve ambiguous object references.
We need the user's search_path to make sampling table rows and running EXPLAIN work when the database objects are not fully-qualified. So, we capture it and pass it down.
> feat(text_to_sql): add a func to resolve ambiguous object references

- projects/pgai/pgai/vectorizer/configuration.py
- projects/pgai/pgai/vectorizer/create_vectorizer.py
- projects/pgai/pgai/vectorizer/generate/docker-compose.yaml
- projects/pgai/pgai/vectorizer/generate/generate.py
In the merge race when litellm and sqlalchemy/alembic was merged we forgot to regenerate the config classes, so did that now.
> feat: add litellm to alembic and python vectorizer creation

- projects/extension/build.py
This PR addresses the bug below that we have been experiencing frequently in CI. When we use `uv run` to run tasks in CI, those tasks do NOT depend on the pgai project being installed. It seems `uv run` will install the pgai package by default since we are running `uv run` in a directory with a pyproject.toml. This PR adds the `--no-project` flag to `uv run` to avoid this behavior.
https://docs.astral.sh/uv/guides/scripts/#running-a-script-without-dependencies
> fix(build): use --no-project flag to uv run for build tasks

- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
We use the `COPY` command with the `BINARY` format in Vectorizer to load embeddings into the target table. To do so, we have to tell psycopg the types of the columns we are copying into. The `set_types` function can take type names or oids of types. We used type names but discovered this is incompatible with some types/domains we encountered.
This PR switches to using OIDs.
The pgai extension can continue to send types, but the vectorizer worker will ignore them. This is important as we need the worker to be backward-compatible with old extension versions. Instead, it will look up the OIDs of the types on the fly using the postgres catalog. It will do this once -- the first time it attempts to do a COPY.
I will do a follow-up PR to have the extension stop sending the type info. …
> fix: load target column types' oids to use in binary copy cmd

- .gitignore
- projects/pgai/DEVELOPMENT.md
- projects/pgai/compose-dev.yaml
This PR adds a `compose-dev.yaml` file that any developer can use for running both the vectorizer-worker and an instance of postgres with the extension preloaded, all built from source.
I added a new section to the `DEVELOPMENT.md` file on pgai project with instructions on how to run it.
> ci: add compose-dev.yaml file

- projects/extension/sql/idempotent/012-vectorizer-int.sql
- projects/extension/sql/incremental/017-upgrade-source-pk.sql
- projects/extension/tests/vectorizer/test_vectorizer.py
Use format_type() to get the correct rendering of the SQL data types for a vectorizer's primary key columns. This supports more types. It supports types and domains defined in other schemas too.
> fix(vectorizer): use format_type to get primary key data types

- projects/pgai/pgai/vectorizer/loading.py
- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/tests/vectorizer/cli/test_vectorizer_core.py
- projects/pgai/tests/vectorizer/cli/test_vectorizer_document.py
Just modifies the query to make it work with composite primary keys.
Some s3 tests have been commented before taking a final decision on retries
due to `EmbeddingProviderError` cases.
> fix: rework requeue_or_remove_work_query

- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/tests/vectorizer/cassettes/test_regression_source_table_has_locked_column.yaml
- projects/pgai/tests/vectorizer/cli/test_vectorizer_core.py
The WHERE clause references the 'locked' column in a JOIN between the user's source table, and our 'locked_items' CTE. The 'locked_items' CTE has a 'locked' column, but the user's source table could _also_ have a 'locked' column, in which case the column reference is ambiguous.
> fix: fully qualify 'locked' column

- .github/workflows/check-markdown-links.yml
- DEVELOPMENT.md
- SECURITY.md
- docs/model_calling/anthropic.md
- docs/model_calling/moderate.md
- docs/structured_retrieval/text_to_sql.md
- docs/vectorizer/api-reference.md
- docs/vectorizer/python-integration.md
- docs/vectorizer/quick-start-voyage.md
- docs/vectorizer/worker.md
- projects/extension/DEVELOPMENT.md
- projects/extension/RELEASE_NOTES.md
- projects/pgai/CHANGELOG.md
- projects/pgai/DEVELOPMENT.md
This PR fixes all markdown links in our docs. 
I used `lychee --exclude-loopback --accept '403'`, as we run in our GH actions.
Pending to add this into the dev dockerfile, but won't happen in this PR.
> docs: fix broken links in markdown files

- .github/workflows/ci.yml
Since now our CI runs on the base branch, we are having conflicts whenever a build runs in parallel. See the error:
With this change, we are generating the group considering the ref of the branch of the PR.
> ci: fix concurrency group to avoid conflicts with main

- .github/workflows/ci.yml
- .github/workflows/merge-gatekeeper.yaml
Fixes concurrency relying on `github.event.pull_request.head.ref` given that
the current reference doesn't exist, but couldn't blame the author, github docs aren't great,
retrieved the info for pull_request events from [this](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#get-a-review-comment-for-a-pull-request) doc.
Then adds a new workflow so we can make it the only mandatory,
it'll make sure that all the triggered workflows have passed. 
This way we can avoid having to bypass checks merging docs,
which are no longer triggering code builds.
> chore: fix concurrency & add new workflow to rule them all

- llms.txt
- scripts/generate_llms_txt.py
I asked claude code to build us a generator for an llms.txt.
It uses the anthropic API to summarize and categorize our docs and example files, and groups them into relevant sections for the llms.txt.
This allows us to simply run the script when we add new files instead of having to manually maintain the file, the temp is set to zero so the result is actually deterministic. I think it is pretty decent.
To run the script simply run `uv run scripts/generate_llms_txt.py` the dependencies are defined inline in the file (uv is awesome like that).
> docs: add llms.txt and generator for it

- projects/pgai/pgai/vectorizer/embedders/litellm.py
- projects/pgai/pgai/vectorizer/embedders/ollama.py
- projects/pgai/pgai/vectorizer/embedders/openai.py
- projects/pgai/pgai/vectorizer/embedders/voyageai.py
- projects/pgai/pgai/vectorizer/embeddings.py
- projects/pgai/tests/vectorizer/test_embeddings.py
The OpenAI API has an undocumented limit on the maximum number of tokens that can be sent in a single API call: 600'000.
This change improves the batching logic to adhere to both constraints of max_chunks_per_batch and max_tokens_per_batch.
> fix: respect OpenAI token limit

- projects/pgai/pgai/vectorizer/embedders/openai.py
The 'Total tokens in batch' log was printed for each document in a batch, now it only prints once, once all documents are processed.
> chore: make token count log less verbose

- .github/workflows/merge-gatekeeper.yaml
we've seen failures on CI due to the default timeout. bumping it to avoid them.
example [run](https://github.com/timescale/pgai/actions/runs/13660426915/job/38190070031) where everything was green but lasted more than 10m.
> fix: avoid timeouts on merge-gatewkeeper

- projects/extension/Dockerfile
- projects/extension/build.py
- projects/extension/pyproject.toml
- projects/extension/uv.lock
- The venv in the extension's docker container only needs the dev dependencies in it.
- Moves the venv in the docker container to a path that is not mounted, so that the venv in the container cannot clash with the one on the host
- the requests library was missing from the dev dependencies in pyproject.toml
> move ext venv in docker image and add missing dependency

- projects/extension/DEVELOPMENT.md
- projects/extension/Dockerfile
- projects/extension/build.py
- projects/extension/tests/contents/test_contents.py
- projects/extension/tests/dump_restore/test_dump_restore.py
- projects/extension/tests/privileges/test_privileges.py
- projects/extension/tests/test_ollama.py
- projects/extension/tests/upgrade/test_upgrade.py
- projects/pgai/tests/vectorizer/conftest.py
mounts the entire repo from the host into the extension dev container. this makes it easier to test examples, access git info, etc.
> build(extension): mount entire repo in ext dev container

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/vectorizer.py
In b242d7049a1c38785c510f0a5a36af31537cb610 we introduced a fix for broken UUID serialization. Unfortunately this fix doesn't apply to consumers of pgai as a library.
This change moves the fix from the cli to the upper-most level in the worker.
> fix: move UUID PK serialization into pgai lib

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/parsing.py
- projects/pgai/tests/test_model_download.py
- projects/pgai/tests/vectorizer/conftest.py
Adding a `pgai vectorizer download-models` command that allows eagerly triggering a docling model download. This allows us to download the models while building our cloud image, instead of the lambda downloading the files new on each invocation.
> feat: add download-models command

- projects/extension/sql/idempotent/909-text-to-sql-openai.sql
The signature of the `ai.openai_chat_complete` function changed and broke text-to-sql. This fixes it
> fix(text_to_sql): deal with changes to ai.openai_chat_complete

- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/pyproject.toml
- projects/pgai/tests/vectorizer/test_vectorizer.py
- projects/pgai/uv.lock
A table can have columns in order `A, B, C, D` and a primary key defined in order `A, D, C, B`. When we select items from the source table, we get the records using table column order (not primary key order). When copying into the target table, we were using primary key ordering to construct the SQL command, but table column order to provide the values. This is a bug.
> fix(vectorizer): always use column ordering from table rather than primary key ordering

- .github/workflows/check-markdown-links.yml
- .github/workflows/ci.yml
Our markdown links checker is failing on releases, due to release-please generating yet non existing links. Exclude those types of links from being analyzed.
Also stop running CI for mere changes in workflows.
Workflow failing on release, due to future, non existing links:
https://github.com/timescale/pgai/actions/runs/13950810027
And passing after testing the fix:
https://github.com/timescale/pgai/actions/runs/13950938884/job/39049990520
> fix: exclude future links from being analyzed

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/tests/vectorizer/test_vectorizer.py
This PR moves the `cli.run_worker` function to a `.run` method in the Vectorizer class. 
This new method can be called from any port, such as CLI or a Lambda, so this becomes the main entry point for processing a vectorizer.
For example this is the main difference in the changes on the methods API: 
Previous call:
```python
await cli.run_vectorizer(
db_url, vectorizer_actual, 1, features, worker_tracking
)
```
New call:
```python
await vectorizer_actual.run(db_url, features, worker_tracking, 1)
```
> feat: add vectorizer.run method

- projects/extension/Dockerfile
PR adds the timescaledb-toolkit to the docker image built for the extension. This allows using the dev image to work with the datasets that are documented in the [tutorials](https://docs.timescale.com/tutorials/latest/) in the docs which relies on functions from the toolkit.
> feat: add timescaledb-toolkit to ext dockerfile

- projects/pgai/pgai/cli.py
Running `pgai --help` or `pgai install` was taking >5s. That's long enough to assume something is broken and wonder if it will run.
Importing some packages on demand takes it down to 0.2s.
BEFORE
AFTER
> fix: make pgai --help faster

- projects/pgai/pgai/vectorizer/processor.py
- projects/pgai/pgai/vectorizer/vectorizer.py
Grouped exceptions were not being printed, just a message saying that the vectorizer failed with a certain number of sub-exceptions.
Adds vectorizer_id to errors whenever possible.
closes #594
> fix: print error messages from grouped exceptions

- projects/extension/ai/vectorizer.py
I tried to also create a test for this, but since the function is in the bundled ai library I have a hard time mocking the httpx call. I could call the function outside of the postgres context but then I need to mock the plpy call at which point... I'm not testing much anymore. Bit annoying, I guess we'll just live with it?
> fix: send top level destination fields in updateembeddings request

- projects/pgai/db/build.py
- projects/pgai/db/justfile
- projects/pgai/justfile
In the extension, we didn't check in built SQL until it was being released; we built the SQL in CI and tested the output. Thus, there was no way for the source to mismatch what was being tested.
This is not the case in the pgai library. You can change the source and forget to build and check in the output.
This PR adds a check to ensure that the built source matches what is checked in to the library.
> test: check that the sql in the library matches the source

- projects/pgai/db/sql/incremental/029-add-vectorizer-name-column.sql
- projects/pgai/pgai/data/ai.sql
Its a character that has to be quoted.
> fix: remove dash from vectorizer name

- docs/vectorizer/api-reference.md
- projects/pgai/pgai/vectorizer/processing.py
- projects/pgai/pgai/vectorizer/vectorizer.py
This wont work if you are using a BYTEA column for documents. Handling that would be a bit more complicated.
Also no idea how to write a test for this.
> chore: reduce default batch_size for loading_uri

- projects/pgai/pgai/cli.py
Changes the argument from:
python -m pgai install --strict true -d 'postgres://a:b@localhost/c'
To:
python -m pgai install --strict -d 'postgres://a:b@localhost/c'
> feat: change --strict argument of install to flag

- .github/workflows/check-markdown-links.yml
- docs/vectorizer/alembic-integration.md
- docs/vectorizer/python-integration.md
- docs/vectorizer/sqlalchemy-integration.md
Separate the various Python integrations into separate files. This makes it easier to discover and link to the right thing.
> docs: breakout python integrations

- projects/pgai/pgai/semantic_catalog/describe.py
- projects/pgai/pgai/semantic_catalog/loader.py
- projects/pgai/tests/semantic_catalog/data/cagg.sql
- projects/pgai/tests/semantic_catalog/data/procedures.json
- projects/pgai/tests/semantic_catalog/data/render_description_to_sql.expected
- projects/pgai/tests/semantic_catalog/data/render_procedures.expected
- projects/pgai/tests/semantic_catalog/test_describe.py
- projects/pgai/tests/semantic_catalog/test_loader.py
PR adds support for loading and rendering aggregate functions. The big annoyance is that as `pg_get_functiondef` errors out on aggregate functions, we need to manually put together the create DDL for the function using stuff from the [`pg_aggregate`](https://www.postgresql.org/docs/current/catalog-pg-aggregate.html) table.
> feat: support aggregate functions

- projects/pgai/pgai/semantic_catalog/vectorizer/sentence_tranformers.py
PR largely disables logging from the `sentence-transformers` library as it's mostly "noise" in terms of our usage and what we show to consumers. We will still log errors from the library though, though I'm unsure exactly if/when it might do that.
Before:
```
$ uv run pgai semantic-catalog load -f foo.sql
[04/30/25 08:44:17] INFO     2025-04-30 08:44:17,704 - sentence_transformers.SentenceTransformer - INFO - Use pytorch device_name: mps                                                                                     SentenceTransformer.py:211
INFO     2025-04-30 08:44:17,706 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: nomic-ai/nomic-embed-text-v1.5                                              SentenceTransformer.py:219
[04/30/25 08:44:21] …
```
> fix: disable logging from sentence-transformers

- projects/pgai/pgai/semantic_catalog/vectorizer/vectorizer.py
PR makes it so that don't need to pass `"config_type": "embedding"` as part of the dict passed to `embedding_config_from_dict` as it feels redundant given the name of the function, and that these configs only accept `config_type: "embedding"`, and that the parameters I pass into the function do not really apply to other configs we have.
> fix: set config_type in embedding_config_from_dict

- projects/pgai/pgai/cli.py
PR makes the `--append` option to `describe` a flag, instead of having user pass in `true/false` explicitly. I cannot really see a reason why someone would ever pass in `--append false` vs just not having the flag, and then this makes it easier to actually use `--append` for the true case.
> fix: make describe --append a flag

- projects/pgai/pgai/semantic_catalog/semantic_catalog.py
- projects/pgai/tests/semantic_catalog/test_search.py
PR adds the following methods to the semantic catalog:
* `list_sql_examples`
* `list_facts`
This makes it easy to get all of these objects in the database. I plan to do a follow-up PR for `list_objects`, though I plan to add some additional arguments to filter to specific types of database objects.
> feat: add sc list function for sql_examples and facts

- projects/pgai/pgai/semantic_catalog/semantic_catalog.py
PR improves it so that when trying to run a command that requires the semantic catalog when pgai hasn't been installed, so that instead of the seeing the following exception message:
```
psycopg.errors.UndefinedTable: relation "ai.semantic_catalog" does not exist
LINE 2:             from ai.semantic_catalog
```
will now see:
```
AssertionError: Semantic catalog is not installed, please run: pgai semantic-catalog create
```
which provides actionable advice to the user on how to fix their issue.
> fix: improve sc error message when pgai not installed

- projects/pgai/pgai/semantic_catalog/gen_sql.py
PR fixes some syntax errors I found in `pgai.semantic_catalog.gen_sql.fetch_database_context_alt`, namely:
1. psycopg does not support named placeholders, only numeric one, so `{table}` was causing a parse error. Replaced it with `{}`
2. Passing an empty list or None were treated similarly in terms of not appending the where clause due to how an empty list is evaluated in an if statement.
3. When the where clause was attached, we were not passing parameter for the list of ids
While this seemingly fixes running this code, I am still not able to end-to-end use the alternative context modes when generating sql.
> fix: syntax errors in fetch_database_context_alt

- projects/pgai/pgai/cli.py
By default dotenv searches the python script path not cwd for the .env. We actually want the cwd.
> fix: use cwd for dotenv

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/semantic_catalog/describe.py
Adds a `--dry-run` flag to `describe` that will cause it to print the objects found but exits before describing them.
> feat: add --dry-run flag to describe command

- projects/pgai/pgai/cli.py
PR makes it so that we use `openai:gpt-4.1` as the default for `semantic-catalog generate-sql` command instead of `anthropic:claude-3-7-sonnet-latest`. This makes it so that the entire semantic-catalog commands default to openai (create, describe, generate-sql).
An upside is that gpt-4.1 is also cheaper than claude-3-7-sonnet-latest and should have relatively similar quality, but haven't tested extensively.
> feat: use openai:gpt-4.1 as default for generate_sql

- projects/pgai/tests/vectorizer/cli/conftest.py
Modifying template1 has weird, unexpected effects on subsequent tests in other modules. I sunk more time than I want to admit to figuring out what was going on.
> test: avoid modifying template1

- DEVELOPMENT.md
- projects/pgai/DEVELOPMENT.md
- projects/pgai/compose-dev.yaml
- projects/pgai/pgai/vectorizer/generate/docker-compose.yaml
We didn't update the `compose-dev.yaml` file since the repackaging. That means we were not installing `pgai` in the DB and we were still asking the user to install the extension.
Additionally, we were using the wrong postgres PGDATA path. In particular, we were setting `/home/postgres/pgdata/data` instead of the default in postgres `/var/lib/postgresql/data` because is the one we use in [timescaledb-docker-ha](https://github.com/timescale/timescaledb-docker-ha/blob/master/Dockerfile#L437). 
That means data was never persisted in the host volume.
> ci: install pgai when running dev env through compose-dev.yaml

- projects/pgai/pgai/cli.py
PR fixes the default value of the `mode` parameter so that it matches what's set above, and also so that it's a value that's accepted.
> fix: default value of mode param for sc fix

- projects/pgai/pgai/semantic_catalog/semantic_catalog.py
- projects/pgai/tests/semantic_catalog/test_search.py
PR adds a `semantic_catalog.list_objects` method to get schema objects from the catalog. There's a `objtype` parameter to allow getting specific objects. I had contemplated adding a `objnames` parameter to allow listing more specific objects (e.g. doing `objtype='table column', objnames=['public', 'airport']` could be used to fetch all columns for a specific table, but decided against it as I wasn't sure exactly what the best API for it would be (e.g. allowing partial matching, multiple different `objnames` for it, etc.). I feel like it's easy enough to do the filtering in python for what I need, and we can expand this later as we better understand how people might use it outside of us.
> feat: add semantic_catalog.list_objects method

- projects/pgai/db/sql/idempotent/999-privileges.sql
- projects/pgai/db/sql/incremental/030-add_vectorizer_errors_view.sql
- projects/pgai/db/tests/vectorizer/test_named_vectorizer.py
- projects/pgai/pgai/data/ai.sql
- projects/pgai/pgai/vectorizer/features/features.py
- projects/pgai/pgai/vectorizer/vectorizer.py
- projects/pgai/pgai/vectorizer/worker.py
- projects/pgai/tests/vectorizer/cassettes/test_errors_table_compatibility.yaml
- projects/pgai/tests/vectorizer/cli/test_compatibility.py
This is an improved version of https://github.com/timescale/pgai/pull/683, which was reverted.
This PR considers retrocompatibility with previous versions that have `ai.vectorizer_errors` as table.
> feat: add support for named vectorizers to ai.vectorizer_errors

- projects/pgai/pgai/semantic_catalog/exceptions.py
PR re-exports `pydantic_ai.exceptions.ModelHTTPError` to make it usable by downstream applications. This exception is raised when `agent.run` errors due to the model response endpoint not returning a 200 response (e.g. 429 response will raise this).
> feat: re-export pydantic_ai exception

- projects/pgai/db/sql/idempotent/011-vectorizer-int.sql
- projects/pgai/db/tests/vectorizer/test_named_vectorizer.py
- projects/pgai/db/tests/vectorizer/test_trigger.py
- projects/pgai/db/tests/vectorizer/test_vectorizer.py
- projects/pgai/pgai/data/ai.sql
This PR adds a new signature for the `ai.execute_vectorizer` function that accepts a vectorizer name as input instead of an id.
> feat: support named vectorizers in ai.execute_vectorizer

- projects/pgai/db/justfile
This PR adds a `just db install <target_db>` and `just db install-clean <target_db>` recipe in the db justfile that installs the db from the actual code, useful for development phase.
> ci: add just db install recipe

- projects/pgai/db/sql/idempotent/008-loading.sql
- projects/pgai/db/tests/vectorizer/test_loading.py
- projects/pgai/db/tests/vectorizer/test_vectorizer.py
- projects/pgai/pgai/data/ai.sql
If the loading column had a unsupported type the error message that was being shown was related to the column not existing. Now an invalid type error messages is shown with the supported types.
> fix: incorrect error of column does not exist

- projects/pgai/db/sql/incremental/030-add_vectorizer_errors_view.sql
- projects/pgai/pgai/data/ai.sql
We have been seeing errors when trying to grant permissions on the `ai.vectorizer_errors` view to roles that don't really need to be explicitly granted because they already have privileges to execute `SELECT` queries.
This change reduces the friction on this side, limiting the copy of permissions to roles that are not granted yet + limits the privileges to only `SELECT` as it is all needed.
> fix: skip granting already granted roles when granting permissions to ai.vectorizer_errors view

- .github/workflows/ci.yml
In order to avoid surprises (errors) when trying to do a release ([like in this case](https://github.com/timescale/pgai/actions/runs/15589257654/job/43903735109)) where the docker image build throws an error, I suggest we build the docker image (not push) every time a commit is merged into `main` branch (instead of on each PR, which will increase CI time)
> ci: validate docker image once merged to main

- projects/pgai/Dockerfile
Fixes https://github.com/timescale/pgai/actions/runs/15590246552/job/43907222334
> ci: add compilers for arm64 docker images required for pandas package

- projects/pgai/pgai/cli.py
- projects/pgai/pgai/semantic_catalog/gen_sql.py
PR modifies the `GenerateSQLResponse.messages` value such that it's now a `list[tuple[ModelRequest, ModelResponse]]`, so that we capture both the request to the model as well as its response, where previously we were just capturing the response. This should make introspection of the generate process easier.
As part of this, I removed the `GenerateSQLResponse.final_prompt` value as this is just a duplicate of the final `ModelRequest` object that we have in the messages list.
> fix: store ModelRequest in generate_sql messages list

- projects/pgai/pgai/semantic_catalog/templates/templates/view.j2
PR fixes rendering view comments as currently:
1. They don't output the view table (`table_name` is not defined on view object)
2. It uses `COMMENT ON TABLE` which throws the postgres error `ERROR:  "view_name" is not a table`
> fix: render view comments

- projects/extension/build.py
This path is not named so it doesn't show in `sysconfig.get_path_names` and we have to hard code it. It's affecting cloud.
> fix: remove debian path from sys.path
